local missions = require("missions")
local mission = require(missions.STRIKE_NOKRIS)
local objective = require("strike_nokris.combat_objective")
local opening = require("strike_nokris.opening")(mission, objective)
local gauntlet = require("strike_nokris.gauntlet_start")(mission, objective, opening)
gauntlet = require("strike_nokris.gauntlet")(mission, objective, gauntlet)
local arena = require("strike_nokris.arena")(mission, objective, gauntlet)
local prefight = require("strike_nokris.prefight")(mission, objective, arena)
local boss_portal = require("strike_nokris.boss_portal")(mission, prefight)
local boss_entry = require("strike_nokris.boss_entry")(mission, objective, boss_portal)
local native_phases = require("strike_nokris.native_phase_provider")()
local boss_fight = require("strike_nokris.boss_fight")(mission, objective, boss_entry, native_phases)
boss_fight = require("strike_nokris.boss_adds")(mission, objective, boss_fight)
local presentation = require("strike_nokris.encounter_presentation")(mission, boss_fight)
local dialogue = require("strike_nokris.dialogue")(mission, presentation)
local program = require("strike_nokris.directives")(mission, dialogue)
return program
